_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./COCO-InstanceSegmentation/ISBDATrained/mask_rcnn_R_50_FPN_1x/run4fromrun3/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("ISBDA_dataset_train",)
  TEST: ("ISBDA_dataset_val",)
SOLVER:
  STEPS: (2500,3000)
  MAX_ITER: 4000

