_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./COCO-InstanceSegmentation/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("ISBDA_dataset_train",)
  TEST: ("ISBDA_dataset_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
